# Generated by Django 4.2.7 on 2026-03-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('cap_id', models.CharField(max_length=50, unique=True)),
                ('number', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('items_json', models.TextField(default='[]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarters', models.CharField(default='', max_length=200)),
                ('postal', models.CharField(default='', max_length=200)),
                ('secure_comms', models.CharField(default='', max_length=200)),
                ('inquiries_email', models.CharField(default='', max_length=200)),
                ('disclaimer', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='DroneSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('system_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('system_class', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('DEVELOPMENT', 'Development'), ('PROTOTYPE', 'Prototype')], default='OPERATIONAL', max_length=20)),
                ('specs_json', models.TextField(default='[]')),
                ('features_json', models.TextField(default='[]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
